version: '2'

services:

  spark:
    build: .
    ports:
      - "8887:9001"
    volumes:
      - ./warcbase-core:/warcbase-core
    environment:
      - "EXTRA_CLASSPATH=/warcbase/warcbase-core/target/warcbase-core-0.1.0-SNAPSHOT-fatjar.jar"

  jupyter:
    image: jupyter/all-spark-notebook
    command: "start-notebook.sh"
    ports:
      - "8889:8888"
    volumes:
      - ./warcbase-core:/warcbase-core
    environment:
      - "SPARK_OPTS=--jars /warcbase-core/target/warcbase-core-0.1.0-SNAPSHOT-fatjar.jar"

  zeppelin:
    image: xemuliam/zeppelin
    ports:
      - "8890:8080"
    volumes:
      - ./warcbase-core:/warcbase-core
    environment:
      - "SPARK_SUBMIT_OPTIONS=\"--jars /warcbase-core/target/warcbase-core-0.1.0-SNAPSHOT-fatjar.jar\""

